changed in restricted dependencies

diff --git a/.github/workflows/dependencies-frontend.yaml b/.github/workflows/dependencies-frontend.yaml
--- a/.github/workflows/dependencies-frontend.yaml
+++ b/.github/workflows/dependencies-frontend.yaml
@@ -75,14 +75,32 @@ jobs:
             echo "changed=false" >> $GITHUB_OUTPUT
           fi
 
+      # - name: Check for restricted dependencies
+      #   run: |
+      #     restricted=$(grep ' restricted,' DEPENDENCIES_EMC-FRONTEND || true)
+      #     if [[ -n "$restricted" ]]; then
+      #       echo "The following dependencies are restricted: $restricted"
+      #       exit 1
+      #     fi
+      #   if: steps.dependencies-changed.outputs.changed == 'true'
+
       - name: Check for restricted dependencies
+        if: steps.dependencies-changed.outputs.changed == 'true'
         run: |
-          restricted=$(grep ' restricted,' DEPENDENCIES_EMC-FRONTEND || true)
-          if [[ -n "$restricted" ]]; then
-            echo "The following dependencies are restricted: $restricted"
+          if [[ ! -f DEPENDENCIES_EMC-FRONTEND ]]; then
+            echo "Dependency file not found!"
             exit 1
           fi
-        if: steps.dependencies-changed.outputs.changed == 'true'
+
+          restricted=$(grep -E ', restricted,' DEPENDENCIES_EMC-FRONTEND || true)
+
+          if [[ -n "$restricted" ]]; then
+            echo "The following dependencies are restricted:"
+            echo "$restricted"
+            exit 1
+          else
+            echo "No restricted dependencies found"
+          fi
 
       - name: Upload DEPENDENCIES_EMC-FRONTEND file
         uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
